### ISSUE TITLE
Error when starting the editor container

### ISSUE THREAD

**Issue by mskyttner** [bioatlas/dcatap-swe-docker#1]
The command that starts the editor is in the CMD line of the Dockerfile:

`cd /dcat-editor && node validatorService.js ../config/validator.json 4000`

This errors with:

```
10:10 $ docker-compose logs editor
Attaching to dcatapswedocker_editor_1
editor_1     | module.js:538
editor_1     |     throw err;
editor_1     |     ^
editor_1     | 
editor_1     | Error: Cannot find module '/dcat-editor/validatorService.js'
editor_1     |     at Function.Module._resolveFilename (module.js:536:15)
editor_1     |     at Function.Module._load (module.js:466:25)
editor_1     |     at Function.Module.runMain (module.js:676:10)
editor_1     |     at startup (bootstrap_node.js:187:16)
editor_1     |     at bootstrap_node.js:608:3

```

To locate the startup-scripts, for troubleshooting, do:

```
docker-compose run editor bash

```
and then inspect the startup scripts:

```
cd /dcat-editor/bin
more validatorService.sh
```
Attempting to run `node validatorService.js ../config/validator.json 4000` produces this message:

```
DEBUG: 'failed to load resource (../libs/rdforms/apps/validator/ValidatorService.js)'
DEBUG: { Error: ENOENT: no such file or directory, open '../libs/rdforms/apps/validator/ValidatorService.js'

```

**Comment by mskyttner** [comment]
Since the "editor" is deprecated and no longer supported by MetaSolutions, no fix for this should be expected to appear and this component should be removed. See deprecated status here in this listing: <https://bitbucket.org/metasolutions/?page=2>
